// 見本用の架空データ。実在の人物ではない（ギルドマスターの五島さんだけ本人）。
// Supabase につなぐときは、このファイルの関数を同じ名前・同じ戻り値のまま中身だけ差し替える。

import type { GiaApplicantImport, Guild, IntroRequest, Party, Profile, ProfileContact, Quest } from "./types";

/** 業種の選択肢（本番は sakaba.tags の kind=industry） */
export const industryOptions = [
  "IT・Web",
  "士業",
  "建設",
  "不動産",
  "飲食",
  "小売",
  "製造",
  "マーケティング",
  "デザイン",
  "教育・研修",
  "健康・医療",
  "美容",
  "金融・保険",
  "その他",
];

export const regionOptions = [
  "オンライン",
  "北海道", "青森", "岩手", "宮城", "秋田", "山形", "福島",
  "茨城", "栃木", "群馬", "埼玉", "千葉", "東京", "神奈川",
  "新潟", "富山", "石川", "福井", "山梨", "長野", "岐阜", "静岡", "愛知",
  "三重", "滋賀", "京都", "大阪", "兵庫", "奈良", "和歌山",
  "鳥取", "島根", "岡山", "広島", "山口",
  "徳島", "香川", "愛媛", "高知",
  "福岡", "佐賀", "長崎", "熊本", "大分", "宮崎", "鹿児島", "沖縄",
];

/** 見本の本人の連絡先（紹介が承諾された相手にだけ見える） */
export const myContact: ProfileContact = {
  profile_id: "p-morita",
  email: "sample@example.com",
  line_url: "",
  website_url: "https://example.com",
};

/** 見本：この人が以前 gia-next に書いていた内容 */
export const myGiaApplicant: GiaApplicantImport = {
  name: "森田 陽介",
  headline: "中小企業のホームページ・LP制作",
  job_title: "Web制作",
  location: "東京\n神奈川",
  services_summary: "ホームページ制作 / 採用ページ制作 / 更新の代行",
  want_to_connect_with: "士業の先生、採用に困っている経営者",
};

export const guild: Guild = {
  id: "g-gia",
  slug: "gia",
  name: "GIAギルド",
  terms: {
    member: "なかま",
    quest: "クエスト",
    party: "パーティ",
    master: "ギルドマスター",
    status: "ステータス",
  },
};

/** 見本の「きょう」。本番ではサーバーで日本時間の日付を使う */
export const TODAY = "2026-09-15";

/** 見本でログインしている人 */
export const ME_ID = "p-morita";
export const MASTER_ID = "p-goto";

export const profiles: Profile[] = [
  {
    id: "p-goto",
    display_name: "五島 一将",
    photo_url: null,
    headline: "GIA代表。人と仕事をつなぐ",
    industry: "IT・Web",
    job: "経営者",
    job_icon: "owner",
    region: "東京",
    bio: "アプリ開発と経営者コミュニティの運営をしています。",
    can_help_with: "仕組み化・アプリ化の相談、人の紹介",
    keywords: ["アプリ開発", "紹介", "経営者"],
    strengths: "人と人の間に立つこと",
    values_text: "紹介した人が得をすること",
    vision: "依頼が集まり、ちゃんとつながる場所をつくる",
    looking_for: "現場を持っている経営者",
    want_to_meet: "本気で事業を伸ばしたい人",
    role: "owner",
    visible_groups: ["work", "values", "connect"],
    accept_intro: true,
    joined_at: "2026-09-01",
  },
  {
    id: "p-morita",
    display_name: "森田 陽介",
    photo_url: null,
    headline: "中小企業のホームページ・LP制作",
    industry: "IT・Web",
    job: "Web制作",
    job_icon: "web",
    region: "東京",
    bio: "従業員10〜50名の会社のホームページと採用ページを作っています。",
    can_help_with: "ホームページ・採用ページの制作、更新の仕組みづくり",
    keywords: ["ホームページ", "採用ページ", "LP"],
    strengths: "",
    values_text: "作ったあと、社内で更新できること",
    vision: "",
    looking_for: "税理士さん・弁護士さんとのつながり",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work", "connect"],
    accept_intro: true,
    joined_at: "2026-09-05",
  },
  {
    id: "p-saeki",
    display_name: "佐伯 美穂",
    photo_url: null,
    headline: "飲食・小売に強い税理士",
    industry: "士業",
    job: "税理士",
    job_icon: "tax",
    region: "大阪",
    bio: "開業3年以内の飲食店・小売店の顧問を中心にしています。オンライン対応可。",
    can_help_with: "決算・資金繰り・融資の相談",
    keywords: ["決算", "融資", "飲食店"],
    strengths: "数字を平易な言葉で説明すること",
    values_text: "社長が数字を怖がらなくなること",
    vision: "関西の飲食店の廃業を減らす",
    looking_for: "飲食店オーナー",
    want_to_meet: "店舗を増やしたい経営者",
    role: "member",
    visible_groups: ["work", "values", "connect"],
    accept_intro: true,
    joined_at: "2026-09-03",
  },
  {
    id: "p-kawashima",
    display_name: "川島 健一",
    photo_url: null,
    headline: "注文住宅とリフォームの工務店",
    industry: "建設",
    job: "工務店経営",
    job_icon: "build",
    region: "埼玉",
    bio: "社員12名の工務店を経営しています。新築とリフォームが半々です。",
    can_help_with: "住宅・店舗の施工、職人の手配",
    keywords: ["工務店", "リフォーム", "採用"],
    strengths: "現場の段取り",
    values_text: "",
    vision: "若い職人が辞めない会社にする",
    looking_for: "採用を手伝ってくれる人",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work", "values", "connect"],
    accept_intro: true,
    joined_at: "2026-09-02",
  },
  {
    id: "p-noguchi",
    display_name: "野口 さやか",
    photo_url: null,
    headline: "博多で居酒屋を2店舗",
    industry: "飲食",
    job: "飲食店オーナー",
    job_icon: "food",
    region: "福岡",
    bio: "居酒屋を2店舗経営しています。3店舗目を考え中です。",
    can_help_with: "飲食店の立ち上げ・スタッフ教育の相談",
    keywords: ["居酒屋", "多店舗", "スタッフ教育"],
    strengths: "",
    values_text: "常連さんが友達を連れてくる店",
    vision: "",
    looking_for: "決算を相談できる税理士",
    want_to_meet: "多店舗展開をした先輩",
    role: "member",
    visible_groups: ["work", "connect"],
    accept_intro: true,
    joined_at: "2026-09-08",
  },
  {
    id: "p-ishii",
    display_name: "石井 拓海",
    photo_url: null,
    headline: "BtoBのマーケティング支援",
    industry: "マーケティング",
    job: "マーケター",
    job_icon: "marketing",
    region: "東京",
    bio: "製造業・士業のWeb集客とセミナー集客を支援しています。",
    can_help_with: "セミナー集客、広告運用、導線設計",
    keywords: ["セミナー", "広告", "BtoB"],
    strengths: "数字で改善を回すこと",
    values_text: "",
    vision: "",
    looking_for: "セミナーを一緒にやれる講師",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work"],
    accept_intro: true,
    joined_at: "2026-09-04",
  },
  {
    id: "p-fujiwara",
    display_name: "藤原 恵",
    photo_url: null,
    headline: "空き家と古民家の再生",
    industry: "不動産",
    job: "不動産",
    job_icon: "realestate",
    region: "神奈川",
    bio: "空き家・古民家の買取と再生、民泊への転用を手がけています。",
    can_help_with: "物件探し、空き家活用の相談",
    keywords: ["空き家", "古民家", "民泊"],
    strengths: "地主さんとの交渉",
    values_text: "古い建物を壊さずに使うこと",
    vision: "地方の空き家を仕事の場所に変える",
    looking_for: "空き家で事業をしたい人",
    want_to_meet: "Webで集客できる人",
    role: "member",
    visible_groups: ["work", "values", "connect"],
    accept_intro: true,
    joined_at: "2026-09-06",
  },
  {
    id: "p-ono",
    display_name: "大野 亮",
    photo_url: null,
    headline: "中小企業の契約・労務の弁護士",
    industry: "士業",
    job: "弁護士",
    job_icon: "legal",
    region: "東京",
    bio: "契約書のチェックと、労務トラブルの予防を中心にしています。",
    can_help_with: "契約書の確認、利用規約の作成",
    keywords: ["契約書", "労務", "利用規約"],
    strengths: "",
    values_text: "",
    vision: "",
    looking_for: "",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work"],
    accept_intro: true,
    joined_at: "2026-09-07",
  },
  {
    id: "p-komatsu",
    display_name: "小松 由佳",
    photo_url: null,
    headline: "ロゴと販促物のデザイン",
    industry: "デザイン",
    job: "デザイナー",
    job_icon: "design",
    region: "オンライン",
    bio: "ロゴ・チラシ・名刺・パッケージのデザイン。全国オンラインで対応しています。",
    can_help_with: "ロゴ、チラシ、LPのデザイン",
    keywords: ["ロゴ", "チラシ", "パッケージ"],
    strengths: "お店の雰囲気を形にすること",
    values_text: "",
    vision: "",
    looking_for: "文章を書ける人",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work", "values", "connect"],
    accept_intro: true,
    joined_at: "2026-09-09",
  },
  {
    id: "p-hasegawa",
    display_name: "長谷川 修",
    photo_url: null,
    headline: "管理職研修の講師",
    industry: "教育・研修",
    job: "研修講師",
    job_icon: "teach",
    region: "名古屋",
    bio: "製造業の管理職研修と、若手の定着の研修をしています。",
    can_help_with: "社内研修、登壇",
    keywords: ["研修", "管理職", "定着"],
    strengths: "",
    values_text: "",
    vision: "",
    looking_for: "AIを使った研修ができる人",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work", "connect"],
    accept_intro: false,
    joined_at: "2026-09-10",
  },
  {
    id: "p-murakami",
    display_name: "村上 奈々",
    photo_url: null,
    headline: "京都の整体院",
    industry: "健康・医療",
    job: "整体院",
    job_icon: "health",
    region: "京都",
    bio: "女性向けの整体院を1店舗。産後ケアが中心です。",
    can_help_with: "姿勢・体の不調の相談",
    keywords: ["整体", "産後ケア"],
    strengths: "",
    values_text: "通い続けなくてよい体にすること",
    vision: "",
    looking_for: "",
    want_to_meet: "",
    role: "member",
    visible_groups: ["work", "values"],
    accept_intro: true,
    joined_at: "2026-09-11",
  },
];

export const quests: Quest[] = [
  {
    id: "q-recruit-page",
    creator_id: "p-kawashima",
    title: "職人の採用ページを作れる人を探しています",
    category: "work",
    summary: "求人媒体に頼らず、自社のページから応募が来るようにしたい。",
    body: "今は求人媒体に年100万円ほど払っていますが、応募はほとんど来ません。\n現場の写真と先輩職人の声を載せた採用ページを作りたいです。撮影から相談できる方だと助かります。",
    region: "埼玉",
    deadline: "2026-10-10",
    member_limit: 2,
    is_urgent: true,
    status: "open",
    created_at: "2026-09-12",
    applicant_ids: ["p-morita"],
  },
  {
    id: "q-izakaya-tax",
    creator_id: "p-noguchi",
    title: "3店舗目を出す前に、決算を一緒に見てほしい",
    category: "consult",
    summary: "今の数字で3店舗目を出してよいか判断したい。",
    body: "2店舗の決算書はあるのですが、正直よく読めていません。\n飲食店に詳しい税理士さんに、一度数字を見てもらいたいです。",
    region: "福岡（オンライン可）",
    deadline: null,
    member_limit: 1,
    is_urgent: false,
    status: "open",
    created_at: "2026-09-13",
    applicant_ids: [],
  },
  {
    id: "q-akiya-biz",
    creator_id: "p-fujiwara",
    title: "古民家を使った事業を一緒に考えませんか",
    category: "collab",
    summary: "鎌倉の古民家1棟。宿・教室・撮影スタジオなど使い方を探しています。",
    body: "鎌倉で古民家を1棟再生しました。\n宿にするか、教室やスタジオとして貸すか、まだ決めていません。場所を使って事業をしたい方、集客を手伝える方と組みたいです。",
    region: "神奈川",
    deadline: null,
    member_limit: 3,
    is_urgent: false,
    status: "open",
    created_at: "2026-09-10",
    applicant_ids: ["p-komatsu", "p-ishii"],
  },
  {
    id: "q-ai-training",
    creator_id: "p-hasegawa",
    title: "管理職向け「AIの使い方」研修の登壇者",
    category: "work",
    summary: "製造業の管理職30名に、2時間の研修をお願いできる方。",
    body: "取引先の製造業から依頼がありました。難しい話ではなく、明日から使える内容を2時間でお願いしたいです。",
    region: "名古屋",
    deadline: "2026-11-20",
    member_limit: 1,
    is_urgent: false,
    status: "in_progress",
    created_at: "2026-09-05",
    applicant_ids: ["p-goto"],
  },
  {
    id: "q-seminar-cohost",
    creator_id: "p-ishii",
    title: "士業向けセミナーを共催できる方",
    category: "collab",
    summary: "集客はこちらで。話す内容を持っている方を探しています。",
    body: "士業の先生向けに、オンラインセミナーを月1回やっています。集客と配信はこちらで行うので、テーマを持っている方と組みたいです。",
    region: "オンライン",
    deadline: null,
    member_limit: 2,
    is_urgent: false,
    status: "open",
    created_at: "2026-09-14",
    applicant_ids: [],
  },
  {
    id: "q-seitai-lp",
    creator_id: "p-murakami",
    title: "整体院のLPを見直したい",
    category: "consult",
    summary: "予約が月に数件しか入らないLPを直したい。",
    body: "文章とデザインの両方を見てもらいました。",
    region: "京都（オンライン可）",
    deadline: null,
    member_limit: 2,
    is_urgent: false,
    status: "completed",
    created_at: "2026-09-02",
    applicant_ids: ["p-komatsu", "p-ishii"],
  },
];

export const parties: Party[] = [
  {
    id: "party-seitai-lp",
    name: "整体院LP改善パーティ",
    quest_id: "q-seitai-lp",
    member_ids: ["p-murakami", "p-komatsu", "p-ishii"],
    formed_at: "2026-09-09",
  },
];

export const introRequests: IntroRequest[] = [
  // 見本の本人（森田）が出した依頼
  {
    id: "r-1",
    requester_id: "p-morita",
    target_id: "p-saeki",
    quest_id: null,
    purpose: "consult",
    message: "制作会社の決算の見方を一度教わりたいです。",
    status: "reviewing",
    outcome: null,
    created_at: "2026-09-14",
    updated_at: "2026-09-14",
  },
  {
    id: "r-2",
    requester_id: "p-morita",
    target_id: "p-ono",
    quest_id: null,
    purpose: "work",
    message: "お客様のサイトに載せる利用規約を見ていただきたいです。",
    status: "proposed",
    outcome: null,
    created_at: "2026-09-12",
    updated_at: "2026-09-13",
  },
  {
    id: "r-3",
    requester_id: "p-morita",
    target_id: "p-komatsu",
    quest_id: null,
    purpose: "collab",
    message: "LP制作で、デザインをお願いできる方を探しています。",
    status: "accepted",
    outcome: null,
    created_at: "2026-09-08",
    updated_at: "2026-09-11",
  },
  {
    id: "r-4",
    requester_id: "p-morita",
    target_id: "p-kawashima",
    quest_id: "q-recruit-page",
    purpose: "work",
    message: "採用ページのクエストを見ました。一度お話を伺いたいです。",
    status: "introduced",
    outcome: "working",
    created_at: "2026-09-12",
    updated_at: "2026-09-14",
  },
  // 見本の本人（森田）への打診
  {
    id: "r-5",
    requester_id: "p-fujiwara",
    target_id: "p-morita",
    quest_id: "q-akiya-biz",
    purpose: "collab",
    message: "古民家の予約ページを作れる方を探しています。",
    status: "proposed",
    outcome: null,
    created_at: "2026-09-13",
    updated_at: "2026-09-14",
  },
  // ほかの人どうし（ギルドマスター画面で見える）
  {
    id: "r-6",
    requester_id: "p-noguchi",
    target_id: "p-saeki",
    quest_id: "q-izakaya-tax",
    purpose: "consult",
    message: "クエストに書いた件で、佐伯さんにお願いしたいです。",
    status: "requested",
    outcome: null,
    created_at: "2026-09-15",
    updated_at: "2026-09-15",
  },
  {
    id: "r-7",
    requester_id: "p-ishii",
    target_id: "p-fujiwara",
    quest_id: null,
    purpose: "info",
    message: "空き家の活用事例をセミナーで紹介させてもらえないかと思っています。",
    status: "requested",
    outcome: null,
    created_at: "2026-09-14",
    updated_at: "2026-09-14",
  },
  {
    id: "r-8",
    requester_id: "p-kawashima",
    target_id: "p-hasegawa",
    quest_id: null,
    purpose: "work",
    message: "若手職人向けの研修をお願いしたいです。",
    status: "declined_by_target",
    outcome: null,
    created_at: "2026-09-06",
    updated_at: "2026-09-08",
  },
  {
    id: "r-9",
    requester_id: "p-murakami",
    target_id: "p-komatsu",
    quest_id: "q-seitai-lp",
    purpose: "work",
    message: "LPのデザインをお願いしたいです。",
    status: "introduced",
    outcome: "met",
    created_at: "2026-09-03",
    updated_at: "2026-09-05",
  },
];

// ---- 取得関数（本番ではここを Supabase の RPC に差し替える） ----

export function getProfile(id: string): Profile | undefined {
  return profiles.find((p) => p.id === id);
}

export function getQuest(id: string): Quest | undefined {
  return quests.find((q) => q.id === id);
}

/** 名鑑に出す仲間（ギルドマスター本人も含む） */
export function listMembers(): Profile[] {
  return profiles;
}

/** 出した人か参加した人として関わり、クリアになったクエストの数 */
export function questClearCount(profileId: string): number {
  return quests.filter(
    (q) => q.status === "completed" && (q.creator_id === profileId || q.applicant_ids.includes(profileId)),
  ).length;
}

export function partyCount(profileId: string): number {
  return parties.filter((p) => p.member_ids.includes(profileId)).length;
}
